name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Zig 0.11.0
      run: |
        wget https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
        tar -xf zig-linux-x86_64-0.11.0.tar.xz

    - name: Run tests
      run: make test ZIG=zig-linux-x86_64-0.11.0/zig RUN_SLOW_TESTS=true
